@host = http://localhost:3001

DELETE {{host}}/api/persons/4 http/1.1

###
GET {{host}}/api/persons http/1.1

###
POST {{host}}/api/persons http/1.1
content-type: application/json

{
    "name": "Ronaldo",
    "number": "112"
}