@host = http://localhost:3001

GET {{host}}/api/persons http/1.1

###
GET {{host}}/api/persons/6076fd9c86b37d371e3d8c73 http/1.1

###
DELETE {{host}}/api/persons/6076fd9c86b37d371e3d8c73 http/1.1

###
POST {{host}}/api/persons http/1.1
content-type: application/json

{
    "name": "Donald Trump",
    "number": "147"
}